export const EXPENSE_CATEGORIES = [
    "Food",
    "Ration",
    "Going out",
    "Eating out",
    "Transport",
    "Shopping",
    "Daily needs",
    "Clothes and accessories",
    "Rent",
    "Utilities",
    "Taxes",
    "Gifts",
    "Bills",
    "Entertainment",
    "Healthcare",
    "Education",
    "Travel",
    "Other",
] as const;